project:
  type: website
  render:
    - "*.qmd"
    - pages/*.qmd

website:
  title: "EEE Digital"
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/about.qmd
        text: About
      - href: pages/undergraduate.qmd
        text: Undergraduate Projects
      - href: exercises
        text: Vercises
      - href: kmaps
        text: Kmaps
  
format:
  html:
    theme:
      - cosmo
      - brand
      # - darkly
    css: styles.css
    toc: true



