project:
  type: website
  render:
    - "*.qmd"
    - pages/**/*.qmd  
  post-render:
    - cp static_apps/FSM_simulatEEE.html _site/

website:
  title: "EEE Digital"
  favicon: logo.png
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/about.qmd
        text: About
      - href: pages/undergraduate.qmd
        text: Undergraduate Projects
      - href: exercises
        text: Vercises
      - href: pages/verilogCrashCourse/index.qmd
        text: Verilog Crash Course
      - href: kmapgameee
        text: kmap-gamEEE
      - href: FSM_simulatEEE.html
        text: FSMsimulatEEE
  
format:
  html:
    theme:
      - cosmo
      - custom.scss
      # - darkly
    css: styles.css
    toc: true
    code-overflow: wrap
    code-block-bg: true
    code-line-numbers: true
    code-block-border-left: "#6B0D1A"




