name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: [self-hosted,digitaleee]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          environment-file: env.yml
          activate-environment: digital_eee_upd
          auto-activate-base: false

      - name: Check conda env
        shell: bash -l {0}
        run: |
          mamba info
          mamba list

      - name: Render Quarto site
        shell: bash -l {0}
        run: |
          quarto render

      - name: Rebuild and restart containers
        run: | 
          docker compose down
          docker compose up -d
          docker system prune -f
