name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: [self-hosted,digitaleee]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Render Quarto site
        run: quarto render

      - name: Rebuild and restart containers
        run: | 
          docker compose down
          docker compose up -d
          docker system prune -f
