name: Deploy

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [vercises-deploy]

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: [self-hosted,digitaleee]

    steps:
    - name: Trigger Unified Root Deployment
      run: sudo -u lawrence /home/lawrence/workspace/deploy.sh